-- MySQL Script generated by MySQL Workbench
-- Sat Sep 25 16:16:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Wintter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Wintter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Wintter` DEFAULT CHARACTER SET utf8 ;
USE `Wintter` ;

-- -----------------------------------------------------
-- Table `Wintter`.`conv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`conv` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`conv` (
  `convid` INT NOT NULL,
  `userid1` INT NOT NULL,
  `userid2` INT NOT NULL,
  `convname` VARCHAR(45) NOT NULL,
  `messageid` INT NOT NULL,
  PRIMARY KEY (`convid`),
  INDEX `fk_conv_message1_idx` (`messageid` ASC) VISIBLE,
  CONSTRAINT `fk_conv_message1`
    FOREIGN KEY (`messageid`)
    REFERENCES `Wintter`.`message` (`messageid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`fav`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`fav` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`fav` (
  `favid` INT NOT NULL,
  `tweetid` VARCHAR(45) NULL,
  PRIMARY KEY (`favid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`follow` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`follow` (
  `followerid` INT NOT NULL,
  `followedid` INT NOT NULL,
  PRIMARY KEY (`followerid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`liste`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`liste` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`liste` (
  `listeid` INT NOT NULL,
  `userid` INT NOT NULL,
  `listename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`listeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`message` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`message` (
  `messageid` INT NOT NULL,
  `convid` INT NOT NULL,
  `date` DATE NOT NULL,
  `userid` INT NOT NULL,
  `contenu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`messageid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`reponse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`reponse` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`reponse` (
  `reponseid` INT NOT NULL,
  PRIMARY KEY (`reponseid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`retweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`retweet` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`retweet` (
  `retweetid` INT NOT NULL,
  `userid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`retweetid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.`tweet` ;

CREATE TABLE IF NOT EXISTS `Wintter`.`tweet` (
  `tweetid` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `contenu` VARCHAR(45) NOT NULL,
  `retweet_retweetid` INT NOT NULL,
  `reponseid` INT NOT NULL,
  `favid` INT NOT NULL,
  PRIMARY KEY (`tweetid`),
  INDEX `fk_tweet_retweet1_idx` (`retweet_retweetid` ASC) VISIBLE,
  INDEX `fk_tweet_reponse1_idx` (`reponseid` ASC) VISIBLE,
  INDEX `fk_tweet_fav1_idx` (`favid` ASC) VISIBLE,
  CONSTRAINT `fk_tweet_retweet1`
    FOREIGN KEY (`retweet_retweetid`)
    REFERENCES `Wintter`.`retweet` (`retweetid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tweet_reponse1`
    FOREIGN KEY (`reponseid`)
    REFERENCES `Wintter`.`reponse` (`reponseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tweet_fav1`
    FOREIGN KEY (`favid`)
    REFERENCES `Wintter`.`fav` (`favid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wintter`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wintter`.users ;

CREATE TABLE IF NOT EXISTS `Wintter`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tweetid` INT NOT NULL,
  `convid` INT NOT NULL,
  `followerid` INT NOT NULL,
  `listeid` INT NOT NULL,
  PRIMARY KEY (`userid`),
  INDEX `fk_user_tweet_idx` (`tweetid` ASC) VISIBLE,
  INDEX `fk_user_conv1_idx` (`convid` ASC) VISIBLE,
  INDEX `fk_user_follow1_idx` (`followerid` ASC) VISIBLE,
  INDEX `fk_user_liste1_idx` (`listeid` ASC) VISIBLE,
  CONSTRAINT `fk_user_tweet`
    FOREIGN KEY (`tweetid`)
    REFERENCES `Wintter`.`tweet` (`tweetid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_conv1`
    FOREIGN KEY (`convid`)
    REFERENCES `Wintter`.`conv` (`convid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_follow1`
    FOREIGN KEY (`followerid`)
    REFERENCES `Wintter`.`follow` (`followerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_liste1`
    FOREIGN KEY (`listeid`)
    REFERENCES `Wintter`.`liste` (`listeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
